### ISSUE TITLE
envelope routines:EVP_DecryptFinal_ex:bad decrypt when using of one time pre key test.

### ISSUE THREAD

**Issue by anupsv** [PeculiarVentures/2key-ratchet#32]
Looking at the test for the usage of one time pre key, i found this,

`         
      
    async function Test() {
        const identity = await createIdentity(1);
        const bundle = await createPreKeyBundle(identity);
        bundle.preKey.id = 1;
        bundle.preKey.key = bundle.preKeySigned.key;
        const raw = await bundle.exportProto();
        const bundle2 = await PreKeyBundleProtocol.importProto(raw);
        assert.isFalse(bundle2.preKey.isEmpty());
        assert.isFalse(bundle2.preKeySigned.isEmpty());
        assert.isFalse(bundle2.identity.isEmpty());
    }
`

Although this works, the bundle does get exported and imported correctly with the prekey present, using it in the server example provided, and running the server-client example yields, this error.

    envelope routines:EVP_DecryptFinal_ex:bad decrypt:../deps/openssl/openssl/crypto/evp/evp_enc.c`

Looking around, i found that this happens when the key provided is wrong and it's not able to decrypt but i don't think it's the case here. Any suggestions as to why this could be happening?

**Comment by anupsv** [comment]
Wrote a small piece of code to produce it.

    async function Test() {
    const AliceID = await createIdentity(1);
    const BobID = await createIdentity(2);
    const AlicePreKeyBundle = await createPreKeyBundle(AliceID);
    const messageText = "Hello world!!";

    AlicePreKeyBundle.preKey.id = 1;
    AlicePreKeyBundle.preKey.key = AlicePreKeyBundle.preKeySigned.key;

    const raw = await AlicePreKeyBundle.exportProto();
    const bundle2 = await PreKeyBundleProtocol.importProto(raw);

    const BobRatchet = await AsymmetricRatchet.create(BobID, bundle2);
    
    const BobMessage1 = await BobRatchet.encrypt(Convert.FromUtf8String(messageText));
    const _tmp = await BobMessage1.exportProto();
    
    let prekeymessage = await PreKeyMessageProtocol.importProto(_tmp);
    let message = prekeymessage.signedMessage;

    const cipher = await AsymmetricRatchet.create(AliceID, prekeymessage);
    
    // the decrypt step causes the rejection.
    const text = await cipher.decrypt(message);
    }

**Comment by microshine** [comment]
I've got the same error. I'll check it

**Comment by microshine** [comment]
I found one-time PreKey error for H4 key derivation in `authenticate` function.

I published new version of `2key-ratchet` - v1.0.2

Here is example code which I used to test it
```typescript
import { Identity, PreKeyBundleProtocol, AsymmetricRatchet, PreKeyMessageProtocol } from "2key-ratchet";
import { Convert } from "pvtsutils";

export async function createIdentity(id: number) {
    const identity = await Identity.create(id, 1, 2); // creates identity with 1 signed and 2 one-time prekeys
    return identity;
}

export async function createPreKeyBundle(identity: Identity) {
    const bundle = new PreKeyBundleProtocol();
    await bundle.identity.fill(identity);
    const buf = new Uint8Array(bundle.identity.signature);

    // add preKey
    const preKeyId = 1; // prekey index
    const preKey = identity.preKeys[preKeyId];
    bundle.preKey.id = preKeyId;
    bundle.preKey.key = preKey.publicKey;

    // add preKeySigned
    const preKeySignedId = 0; // signed prekey index
    const preKeySigned = identity.signedPreKeys[preKeySignedId];
    bundle.preKeySigned.id = preKeySignedId;
    bundle.preKeySigned.key = preKeySigned.publicKey;
    await bundle.preKeySigned.sign(identity.signingKey.privateKey);

    bundle.registrationId = 1;

    return bundle;
}

async function Test() {
    const AliceID = await createIdentity(1);
    const BobID = await createIdentity(2);
    const AlicePreKeyBundle = await createPreKeyBundle(AliceID);
    const messageText = "Hello world!!";

    const raw = await AlicePreKeyBundle.exportProto();
    const bundle2 = await PreKeyBundleProtocol.importProto(raw);

    const BobRatchet = await AsymmetricRatchet.create(BobID, bundle2);

    const BobMessage1 = await BobRatchet.encrypt(Convert.FromUtf8String(messageText));
    const _tmp = await BobMessage1.exportProto();

    let prekeymessage = await PreKeyMessageProtocol.importProto(_tmp);
    let message = prekeymessage.signedMessage;

    const cipher = await AsymmetricRatchet.create(AliceID, prekeymessage);

    // the decrypt step causes the rejection.
    const text = await cipher.decrypt(message);
}

Test()
    .then(() => {
        console.log("Success");
    })
    .catch((err) => {
        console.error(err);
    })
```

**Comment by anupsv** [comment]
Hi, i just verified it, it's working correctly. Thanks a lot.

I have a use case question which might be a security concern, So my server has the bundle and the prekey's associated, when a client requests the prekeybundle, is it ok for the server to send the prekeybundle and prekey separately or would it be better if the server imports the bundle, adds a prekey, exports it again and sends it to the client. The prekey will be deleted afterwards.

**Comment by rmhrisk** [comment]
@anupsv see https://whispersystems.org/docs/specifications/x3dh/#publishing-keys which has a description of session authentication. This discusses the how to handle PreKeyBundle publication in X3DH.

In general, though the bundle is signed and should not be trusted unless signed by the identity key so sending in one go should not be required

**Comment by anupsv** [comment]
Oh, i was referring to the One Time prekey's. The document suggests this,

> The server should provide one of Bob's one-time prekeys if one exists, and then delete it. If all of Bob's one-time prekeys on the server have been deleted, the bundle will not contain a one-time prekey.

So by this, i am assuming that the bundle when sent by the server to a new client, the server will choose one of the one time prekey's, export it and send it to the client.

**Comment by anupsv** [comment]
Thank you very much.
