### ISSUE TITLE
No known options for function setEngine

### ISSUE THREAD

**Issue by randomprimate** [PeculiarVentures/2key-ratchet#35]
Using 2key-ratchet requires setting an engine which I couldn't find in the docs. What options are available to include as parameters?

### Steps to Reproduce
* Use [this](https://github.com/PeculiarVentures/2key-ratchet/blob/master/examples/simple.js) example. 
* This raises `Error: WebCrypto engine is empty. Use setEngine to resolve it.`.  
* Set the engine `DKeyRatchet.setEngine('WebCrypto')` 
* This results in `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subtle' of undefined` which is due to the `crypto` [attribute](https://github.com/PeculiarVentures/2key-ratchet/blob/master/src/crypto/crypto.ts#L36) not being declared as far as I can tell.

**Comment by rmhrisk** [comment]
What environment are you running in (browser or node)?

**Comment by microshine** [comment]
`2key-ratchet` has [index.d.ts](https://github.com/PeculiarVentures/2key-ratchet/blob/master/index.d.ts#L649-L656) with types declarations

```typescript
/**
 * Sets crypto engine
 *
 * @export
 * @param {string} name     Name of engine
 * @param {Crypto} crypto   WebCrypto implementation
 */
export function setEngine(name: string, crypto: Crypto): void;
```

it uses Browser Crypto by default but you need to set Crypto in NodeJs.

```typescript
import { Crypto } from "@peculiar/webcrypto";

setEngine("WebCrypto NodeJS", new Crypto());
```

NodeJS WebCrypto implementations:
- [@peculiar/webcrypto](https://github.com/PeculiarVentures/webcrypto)
- [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl)
- [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11)

**Comment by randomprimate** [comment]
@rmhrisk nodejs

@microshine thanks, this is what I was looking for.
Love this https://github.com/PeculiarVentures/webcrypto

Thanks guys, appreciate the assist.

**Comment by rmhrisk** [comment]
@randomprimate would love to hear what your doing with it  :)
