### ISSUE TITLE
Proper way to send messages after initial session is established?

### ISSUE THREAD

**Issue by KyrneDev** [PeculiarVentures/2key-ratchet#41]
Hi,

Apologies for the second issue.

I currently am able to get the first message sent and decrypted, but I am unable to figure out how to properly use SignedMessageProtocol to send new messages.

Do you mind pointing me in the right direction?

**Comment by microshine** [comment]
Have you seen [examples](https://github.com/PeculiarVentures/2key-ratchet/tree/master/examples)?

Please use `ts-node` to run examples

### Install ts-node
```
npm i ts-node -g
```

### Run examples
```
ts-node examples/start.ts
```

**Comment by microshine** [comment]
@KyrneDev You can use this `launch.json` file to debug examples in VS Code

### .vscode/launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run examples",
      "type": "node",
      "request": "launch",
      "args": [
        "${workspaceFolder}/examples/start.ts"
      ],
      "runtimeArgs": [
        "--require",
        "ts-node/register"
      ],
      "outputCapture": "std",
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/7333669/82838952-7ddc4900-9ed6-11ea-9774-50010409122c.png)

**Comment by KyrneDev** [comment]
Thanks guys!
