### ISSUE TITLE
Any suggestions for a group message example?

### ISSUE THREAD

**Issue by amilich** [PeculiarVentures/2key-ratchet#42]
Have been reading the Signal and WhatsApp docs on how they use X3DH to support group messaging. Just wondering - has there been any thought on using `2key-ratchet` for that in it's current version?

**Comment by rmhrisk** [comment]
We have discussed it and it would be relatively straight forward. Pull requests welcome.

**Comment by amilich** [comment]
Awesome. Will take a look.

**Comment by dzcpy** [comment]
I'm also interested in implementing a group chat using this module. Could you shed some light on it?

**Comment by rmhrisk** [comment]
Need to look at how keys are distributed in Signal, first hit on this was https://eprint.iacr.org/2017/713.pdf

**Comment by dzcpy** [comment]
@rmhrisk Thanks! Will take a look
